application: techlionscollege
version: 1
runtime: php55
api_version: 1
#arafat  fff
handlers:
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /assets
  static_dir: views/assets
- url: /images
  static_dir: views/images
- url: /plugins
  static_dir: views/plugins
- url: /bootstrap
  static_dir: views/bootstrap
- url: /dist
  static_dir: views/dist
- url: /backend
  script: backend.php
- url: /login
  script: login.php
- url: /logout
  script: logout.php
- url: /create_department
  script: create_department.php
- url: /create_course
  script: create_course.php
- url: /update_course
  script: update_course.php
- url: /update_department
  script: update_department.php
- url: /remove_course
  script: remove_course.php
- url: /add_hold
  script: add_hold.php
- url: /remove_hold
  script: remove_hold.php
- url: /view_holds
  script: view_holds.php
- url: /remove_coursesection
  script: remove_coursesection.php
- url: /create_coursesection
  script: create_coursesection.php
- url: /add_course
  script: add_course.php
- url: /add_student
  script: add_student.php
- url: /searchcatalog_bycourse
  script: searchcatalog_bycourse.php
- url: /searchcatalog_bydepartment
  script: searchcatalog_bydepartment.php
- url: /searchcatalog_byprofessor
  script: searchcatalog_byprofessor.php
- url: /searchcatalog_bytimeslot
  script: searchcatalog_bytimeslot.php
- url: /drop_student
  script: drop_student.php
- url: /view_studentinformation
  script: view_studentinformation.php
- url: /view_adviser
  script: view_adviser.php
- url: /drop_course
  script: /drop_course.php
- url: /view_gradesbysemester
  script: /view_gradesbysemester.php
- url: /view_studentdetailschedule
  script: view_studentdetailschedule.php
- url: /set_dates
  script: set_dates.php
- url: /view_gradesbytranscript
  script: view_gradesbytranscript.php
- url: /searchschedule_bydepartment
  script: searchschedule_bydepartment.php
- url: /assign_midtermsgrades
  script: assign_midtermsgrades.php
- url: /assign_finalgrades
  script: assign_finalgrades.php
- url: /view_facultymemberadviseelist
  script: view_facultymemberadviseelist.php
- url: /searchschedule_bycourse
  script: /searchschedule_bycourse.php
- url: /view_facultymembercourselist
  script: view_facultymembercourselist.php
- url: /research_studentsinformation
  script: research_studentsinformation.php
- url: /research_facultyinformation
  script: research_facultyinformation.php
- url: /viewstudentgrades_bysemester
  script: viewstudentgrades_bysemester.php
- url: /viewstudentgrades_bytranscript
  script: viewstudentgrades_bytranscript.php
- url: /view_studentschedule
  script: view_studentschedule.php
- url: /update_coursesection
  script: update_coursesection.php
- url: /declare_major
  script: declare_major.php
- url: /delete_major
  script: delete_major.php
- url: /
  script: index.php
- url: /.*
  script: 404.php

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
